<?php

namespace Patrimoine2Bundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Patrimoine2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Patrimoine2Repository extends EntityRepository
{
}
