Patrimoine2Bundle\Entity\Patrimoine2:
    type: entity
    table: null
    repositoryClass: Patrimoine2Bundle\Repository\Patrimoine2Repository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre1:
            type: string
            length: 255
        article1:
            type: text
        image1:
            type: string
            lenght: 255
        titre2:
            type: string
            length: 255
        article2:
            type: text
        image2:
            type: string
            lenght: 255

    lifecycleCallbacks:

      prePersist: [ preUpload1, preUpload2 ]
      preUpdate: [ preUpload1, preUpload2 ]
      postPersist: [ upload1, upload2 ]
      postUpdate: [ upload1, upload2 ]
      postRemove: [ removeUpload1, removeUpload2 ]

